### ISSUE TITLE
Graphics driver ppa oibaf: could not find a distribution template for neon/bionic

### ISSUE THREAD

**Issue by emphasize** [AIIX/Documentation#2]
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 107, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 117, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 612, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 93, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for neon/bionic

From launchpad: 
> Supported Ubuntu versions:
> - 18.04 (bionic) <- supported, but you need to install newer kernel with:
> sudo apt install --install-recommends linux-generic-hwe-18.04

(not yet installed the newer kernel linux-generic-hwe-18.04)

`ppa:paulo-miguel-dias/mesa` with the same result

**Comment by emphasize** [comment]
Don't know why this happened but there is no neon.info/neon.mirror in /usr/share/python-apt/templates. Had to cp Ubuntu.* neon.* to work around. But despite the ppa is added,

> E: Unable to locate package mesa
> E: Unable to locate package libdrm

**Comment by emphasize** [comment]
Apparently these are the two you'd want `sudo apt-get install libgles2-mesa libgles2-mesa-dev`
